Des 157 make functional the olvide mi contrasena option adding email pashe 2 cms
generaciondesafiante/Regresemos_a_nuestra_casa_CMS pull request #11
Opened 2023-08-23 23:14 UTC by Daniielmayo

2023-08-25 13:22 UTC, abdulflorez requested changes
I wrote some comments

2023-08-25 13:22 UTC, abdulflorez commented on controllers/auth.js
> +const jwt = require("jsonwebtoken");
What about changing this for something more clear,  jsonToken

2023-08-25 13:22 UTC, DanielCalleCO requested changes
Hello Dani, could you please review my suggestions?

2023-08-25 13:22 UTC, DanielCalleCO commented on controllers/auth.js
> +      msg: "Por favor hable con el administrador",
```suggestion
      msg: "Por favor comunícate con el administrador",
```

2023-08-25 13:22 UTC, DanielCalleCO commented on controllers/auth.js
> +        msg: "Password incorrecto",
```suggestion
        msg: "Contraseña incorrecta",
```

2023-08-25 13:22 UTC, DanielCalleCO commented on controllers/auth.js
> +      msg: "Por favor hable con el administrador",
```suggestion
      msg: "Por favor comunícate con el administrador",
```

2023-08-25 13:22 UTC, DanielCalleCO commented on controllers/auth.js
> +      msg: "Por favor hable con el administrador",
```suggestion
      msg: "Por favor comunícate con el administrador",
```

2023-08-25 13:22 UTC, DanielCalleCO commented on middlewares/validate-email-reset-password.js
> +    html: `¡Hola! Haga clic en el siguiente enlace para restablecer su contraseña: <br/>
```suggestion
    html: `¡Hola! Haz clic en el siguiente enlace para restablecer tu contraseña: <br/>
```

2023-08-25 13:22 UTC, DanielCalleCO commented on middlewares/validate-email-reset-password.js
> +  const resetLink = `http://localhost:3000/resetPassword/${user.id}/${resetToken}`;
local host

2023-08-25 18:36 UTC, abdulflorez submitted a review, later dismissed

2023-08-25 19:19 UTC, DanielCalleCO requested changes
Nice! Just a simple additional comment before merge...

2023-08-25 19:19 UTC, DanielCalleCO commented on middlewares/validate-email-reset-password.js
> +    html: `¡Hola! esperamos que te encuentres bien. Hemos recibido una solicitud para recuperar la contraseña de tu cuenta  Entendemos lo importante que es para ti acceder a tu cuenta de manera segur
```suggestion
    html: `¡Hola! esperamos que te encuentres bien. <br/>Hemos recibido una solicitud para recuperar tu contraseña. Entendemos lo importante que es para ti acceder a tu cuenta de manera segura.  <br/>Haz clic en el siguiente enlace para restablecer tu contraseña: <br/>
```

2023-08-25 20:45 UTC, DanielCalleCO requested changes

2023-08-25 20:45 UTC, DanielCalleCO commented on middlewares/validate-email-reset-password.js
> +    html: `¡Hola! esperamos que te encuentres bien. <br/>Hemos recibido una solicitud para recuperar tu contraseña. Entendemos lo importante que es para ti acceder a tu cuenta de manera segura.  <br/
Sorry I forgot to let you the last suggestion.

```suggestion
    html: `¡Hola! esperamos que te encuentres bien. <br/>Hemos recibido una solicitud para recuperar tu contraseña. Entendemos lo importante que es para ti acceder a tu cuenta de manera segura.  <br/>Haz clic en el siguiente enlace para restablecerla: <br/>
```

2023-08-25 20:50 UTC, DanielCalleCO approved these changes

2023-08-31 13:04 UTC, abdulflorez approved these changes
Lgtm

2023-08-31 13:08 UTC, merged