Des 243 create proogress status for users in bd and be user
generaciondesafiante/Regresemos_a_nuestra_casa_CMS pull request #27
Opened 2024-01-04 19:57 UTC by Daniielmayo

A logic has been implemented in the updateVideoStatus function that allows you to update the status of a video efficiently, verifying the existence of courses, topics, lessons, and videos before performing operations on the database. Now, all information is stored together and efficiently in a single shipment, avoiding the need for multiple requests for each component.

2024-01-04 20:46 UTC, DanielCalleCO requested changes

2024-01-04 20:46 UTC, DanielCalleCO commented on database/config.js
> +    console.log("Db online");
Could you please add a comment before this line to explain why we decided to keep this console.log? I think it is neccesary

2024-01-09 13:07 UTC, abdulflorez approved these changes

2024-01-09 13:29 UTC, SthefaniaEcheverry approved these changes

2024-01-09 13:41 UTC, DanielCalleCO approved these changes

2024-01-09 14:04 UTC, SthefaniaEcheverry submitted a review, later dismissed

2024-01-19 13:29 UTC, abdulflorez approved these changes

2024-01-19 14:17 UTC, DanielCalleCO approved these changes

2024-01-19 15:38 UTC, merged