create controller last viewed  resource of the course
generaciondesafiante/Regresemos_a_nuestra_casa_CMS pull request #84
Opened 2024-07-30 17:19 UTC by Daniielmayo

2024-08-01 14:02 UTC, abdulflorez requested changes

2024-08-01 14:02 UTC, abdulflorez commented on controllers/user/lastViewedResourceUser.js
> +      courseName: course.nameCourse,
La manera correcta es como esta en el atributo, courseName ya que se refiere al Nombre del curso, no al curso en si

2024-08-01 14:02 UTC, abdulflorez commented on controllers/user/lastViewedResourceUser.js
> +      topicName: topic.nameTopic,
mismo error de tipado aqui

2024-08-01 14:08 UTC, Daniielmayo commented on controllers/user/lastViewedResourceUser.js
> +    if (!mongoose.Types.ObjectId.isValid(userId)) {
Es un atributo netamente de mongo para poder acceder a los id's dentro de la base de datos

2024-08-01 18:53 UTC, abdulflorez approved these changes

2024-08-06 13:12 UTC, generaciondesafiante approved these changes

2024-08-06 13:12 UTC, merged