Implementation and change of the structure of sending password change…
generaciondesafiante/Regresemos_a_nuestra_casa_CMS pull request #90
Opened 2024-08-14 15:01 UTC by Daniielmayo

… and password recovery emails to the user, adaptation of the template for the emails

2024-08-14 15:05 UTC, cristianarce89 submitted a review, later dismissed

2024-08-15 14:19 UTC, abdulflorez approved these changes

2024-08-15 14:52 UTC, DanielCalleCO requested changes

2024-08-15 14:52 UTC, DanielCalleCO commented on controllers/auth/emailUserPasswordForget.js
>      //*Generar nuestro Jwt
Could you please translate this line?

2024-08-15 14:52 UTC, DanielCalleCO commented on middlewares/confirm-mail-changePassword.js
> +        pass: "tfehpymjjkfwsagn",
I'm not sure, but I think here, you should pass the `user.email` not your email, am I right?

Same thing in `pass`

2024-08-22 13:22 UTC, abdulflorez approved these changes

2024-08-22 16:13 UTC, generaciondesafiante approved these changes

2024-08-26 13:35 UTC, DanielCalleCO approved these changes

2024-08-26 13:36 UTC, merged